# Generated by Django 4.2.4 on 2023-09-04 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankaccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='userimage/')),
                ('marital_status', models.CharField(choices=[['single', 'SINGLE'], ['married', 'MAARRIED'], ['others', 'OTHERS']], max_length=100)),
                ('gender', models.CharField(choices=[['male', 'MALE'], ['female', 'FEMALE'], ['other', 'OTHER']], max_length=100)),
                ('identity_type', models.CharField(choices=[['aadhar_card', 'AADHAR_CARD'], ['vooter_id', 'VOOTER_ID'], ['driving_licines', 'DRIVING_LICINES']], max_length=100)),
                ('identity_image', models.ImageField(upload_to='userimage/')),
                ('date_of_birth', models.DateTimeField()),
                ('signature', models.ImageField(upload_to='userimage/')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bankaccounts.account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
