# Generated by Django 4.2.4 on 2023-09-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0003_alter_kyc_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='identity_image',
            field=models.ImageField(upload_to='userimag/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='image',
            field=models.ImageField(upload_to='userimag/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='signature',
            field=models.ImageField(upload_to='userimag/'),
        ),
    ]
